// <auto-generated />
using System;
using System.Text.Json;
using Finance.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finance.Data.Data.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20260517002000_NullableBalances")]
    partial class NullableBalances
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finance.Data.Data.Balance", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTimeOffset>("AsOf").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("BankAccountId").HasColumnType("uuid");
                    b.Property<string>("Currency").IsRequired().HasColumnType("text");
                    b.Property<long?>("CurrentMinorUnits").HasColumnType("bigint");
                    b.Property<JsonDocument>("RawJson").IsRequired().HasColumnType("jsonb");
                    b.Property<Guid>("TenantId").HasColumnType("uuid");
                    b.HasKey("Id");
                    b.HasIndex("TenantId", "BankAccountId", "AsOf").IsUnique();
                    b.ToTable("Balances");
                });
#pragma warning restore 612, 618
        }
    }
}
